version: '3.9'

services:
  web:
    build: .
    command: python /app/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/app/
    depends_on: 
      - db 
  db: 
    image: docker.hamincharkho.pw/databases/postgres:16
    restart: always
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=roozbehsarcheshme1381"
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    
  pgadmin:
    image: docker.hamincharkho.pw/databases/gui/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: roozbehsarcheshme1381
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  db:
    driver: local
  pgadmin:

